name: Publish Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - run: gpg --quiet --batch --yes --decrypt --passphrase="$PASS" --output=secring.gpg secring.gpg.gpg
        env:
          PASS: ${{ secrets.FREEFAIR_SECRING_PASS }}
      - name: Publish package
        run: ./gradlew --no-parallel publishToSonatype closeAndReleaseRepository -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/secring.gpg -Psigning.password=$SIGNING_PASSWORD -Psigning.keyId=$SIGNING_KEY_ID
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
